# Basically move time up front
format = """
$time\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$buf\
$cmake\
$cobol\
$container\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$shell\
$character"""


add_newline = true

# Begin of icons taken from https://starship.rs/presets/nerd-font.html
[aws]
symbol = "  "

[buf]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[rust]
symbol = " "
# End of icons taken from https://starship.rs/presets/nerd-font.html

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red) "

[[battery.display]]
threshold = 50

[container]
format = "[$symbol \\[$name\\]]($style) "

[directory]
read_only = " "
truncation_symbol = "…/"
truncation_length = 2
style = " yellow"

# [env_var]
# variable = "SHELL"
# default = "unknown shell"

[git_branch]
symbol = ""
format = "[$symbol$branch]($style)"

[conda]
symbol = " "
ignore_base = false
format = "[$symbol$environment]($style) "

[python]
symbol = " "
style = "cyan bold"
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[time]
disabled = false
format = '[$time](bold green)[|](red) '
time_format = "%F %T"

[username]
style_user = "yellow bold"
style_root = "black bold"
format = "[$user]($style)[@](red)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[$hostname]($style)[::](red)"
trim_at = ""
style = "yellow bold"
disabled = false
